# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: clean Maven
        run: mvn clean
        
      - name: install maven
        run: mvn install 
        
      - name: compile maven
        run: mvn compile
        
      - name: jar
        run: mvn package
        
        
      - name: List files
        run: ls
        
      - name: Upload the Client jar
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./Client/target/*jar-with-dependencies.jar
          
      - name: Upload the Backend jar
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./Backend/target/*jar-with-dependencies.jar
          
      - name: Upload the Commons jar
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./Common/target/*jar-with-dependencies.jar
          
      - name: Upload the DataAnalyser jar
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./DataAnalyser/target/*jar-with-dependencies.jar
            
